# 特殊关键字和符号

## ::= Syntax 句法规则定义符

1. Modified BNF grammar notation
2. name ::= expression
3. Symbol on the left must be replaced with the expression on the right
4. []: group, none or once. *: none or more. +: one or more
5. (): group, |: alternative, "x": literal character

## [Lexical analysis词法分析](https://docs.python.org/3/reference/lexical_analysis.html)

1. Logical lines
   + token NEWLINE
   + Explicit line joining: \
   + Implicit line joining: (),[],{} 使用逗号分割成多行
   + compound statements 复合声明可以跨越多行, 但是被看作一个logical line
2. Indentation: grouping of statements
3. Identifiers
4. Keywords and Soft Keywords
5. Literals
   + String and Bytes literals 字符串和字节码
   + 都可以使用''或"", 字节码以b或B开头, b''或B""
   + 前缀r或R是raw格式, 不接受escape转义
   + 前缀f或F只支持字符串, 称为f字符串-格式化字符串: f"abc{x}"
6. Operators
7. Delimiters
8. 非法字符: 字符串以外的$, ?, `

In [3]:
a = dict(x=3)
print(a['x'])

3


## := Assignment Expression 表达式赋值符

1. identifier := assignment_expression
2. 把表达式赋值给标识符, 节省了单次或循环多次的赋值操作
3. 只要是把赋值, 条件判断, 执行后续表达式的输入参数合并到一起
4. 需要括号()封装的操作
   + slicing
   + conditional
   + lambda
   + keyword-argument
   + comprehension-if expressions
   + assert statement
   + with statement

In [1]:
if ae1 := [[ae2 := ae3 * 2, ae2 + 1] for ae3 in range(5)]:
  print(ae1)
ae4 = 1
print(ae1[1:(ae5 := ae4 + 2)])

[[0, 1], [2, 3], [4, 5], [6, 7], [8, 9]]
[[2, 3], [4, 5]]


## ... 省略号

In [2]:
# 1. 取代pass, 作为语句块的省略
class Test:
  pass


# 2. 用于赋值省略
x = ...

# 3. 用于numpy ndarray数组取某一维的全部值, ...这里和无左右值的:类似
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = a[..., :]  # 这里逗号左右作用相同
print(b)
c = a[:, (0, 1, 2)]  # ...相当于某一维的索引全部输入成为tuple
print(c)

# 4. 用于类型提示Type Hints
# 4.1 用于tuple
numbers: tuple[int, ...]

# Allowed:
numbers = ()
print(numbers)
numbers = (1,)
print(numbers)
numbers = (4, 5, 6, 99)
print(numbers)

# 4.2 用于callable
from typing import Callable


def add_one(i: int) -> int:
  return i + 1


def multiply_with(i: int, j: int) -> int:
  return i * j


# Callable[..., int] 接受多个参数, 最后一个为返回值为int
def calculate(i: int, action: Callable[..., int], *args: int) -> int:
  return action(i, *args)


# Works:
calculate(1, add_one)
calculate(1, multiply_with, 3)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
()
(1,)
(4, 5, 6, 99)


3

## *, ** iterable packing and unpacking 枚举类型自动打包和解包符号

1. *针对集合, **针对dict字典
2. 函数声明中的型参带*或**为自动打包对象, 打包到一个型参
3. 函数调用中的实参带*或**为自动解包对象, 解包成多个实参
4. 表达式声明中的starred为能够自动解包的集合结构
5. 表达式句法定义中的(x ",")*代表零个或多个x代表的内容